# ansible-playbook -i inventory.ini udm_pxe.yml
---
- name: Configure PXE boot settings for dnsmasq
  hosts: udm
  become: yes
  tasks:

    - name: Ensure the directory exists
      file:
        path: /run/dnsmasq.conf.d
        state: directory
        mode: '0755'

    - name: Create PXE configuration file
      copy:
        dest: /run/dnsmasq.conf.d/PXE.conf
        content: |
          #
          # Generated automatically by Ansible
          #

          # Configuration of PXE boot for '

          # The boot filename, Server name, Server Ip Address
          dhcp-boot=netboot.xyz.kpxe,netboot.xyz,10.10.10.200

          # inspect the vendor class string and match the text to set the tag
          dhcp-vendorclass=BIOS,PXEClient:Arch:00000
          dhcp-vendorclass=UEFI32,PXEClient:Arch:00006
          dhcp-vendorclass=UEFI,PXEClient:Arch:00007
          dhcp-vendorclass=UEFI64,PXEClient:Arch:00009

          # Set the boot file name based on the matching tag from the vendor class (above)
          dhcp-boot=net:UEFI32,netboot.xyz.efi,netboot.xyz,10.10.10.200
          dhcp-boot=net:BIOS,netboot.xyz.kpxe,netboot.xyz,10.10.10.200
          dhcp-boot=net:UEFI64,netboot.xyz.efi,netboot.xyz,10.10.10.200
          dhcp-boot=net:UEFI,netboot.xyz.efi,netboot.xyz,10.10.10.200
        mode: '0644'

    - name: Kill dnsmasq process
      command: bash -c "kill $(cat /run/dnsmasq.pid)"
      ignore_errors: yes