---
- name: Install Homebrew packages on macOS
  hosts: localhost
  connection: local
  become: false

  tasks:
    - name: Configure Bluetooth AAC in Windows Registry
      hosts: all
      become: yes
      tasks:
        - name: Ensure the registry path exists
          ansible.windows.win_regedit:
            path: HKLM:\SYSTEM\CurrentControlSet\Services\BthA2dp\Parameters
            state: present

        - name: Set BluetoothAacEnable DWORD to 0
          ansible.windows.win_regedit:
            path: HKLM:\SYSTEM\CurrentControlSet\Services\BthA2dp\Parameters
            name: BluetoothAacEnable
            type: dword
            data: 0
            # Disable bluetooth headphone hands free in Device Manager to prevent bad sound quality when headphone microphone is selected (e.g. Black Ops 6)